In [2]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
%matplotlib inline

In [3]:
df=pd.read_csv(r'''C:\Users\USER\Desktop\dataset\boston.csv''')
df.head()

C:\Users\USER\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3146: DtypeWarning: Columns (0,2,6,12) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,


INCIDENT_NUMBER  OFFENSE_CODE OFFENSE_CODE_GROUP        OFFENSE_DESCRIPTION  \
0       TESTTEST2           423                NaN       ASSAULT - AGGRAVATED   
1       S97333701          3301                NaN             VERBAL DISPUTE   
2       S47513131          2647                NaN  THREATS TO DO BODILY HARM   
3       I92102201          3301                NaN             VERBAL DISPUTE   
4       I92097173          3115                NaN         INVESTIGATE PERSON   

   DISTRICT REPORTING_AREA SHOOTING     OCCURRED_ON_DATE  YEAR  MONTH  \
0  External                       0  2019-10-16 00:00:00  2019     10   
1        C6            915        0  2020-07-18 14:34:00  2020      7   
2       E18            530        0  2020-06-24 10:15:00  2020      6   
3       E13            583        0  2019-12-20 03:08:00  2019     12   
4       C11            355        0  2019-10-23 00:00:00  2019     10   

  DAY_OF_WEEK  HOUR UCR_PART          STREET        Lat       Long  \
0   Wednesday     0      NaN    RIVERVIEW DR        NaN        NaN   
1    Saturday    14      NaN  MARY BOYLE WAY  42.330813 -71.051368   
2   Wednesday    10      NaN    READVILLE ST  42.239491 -71.135954   
3      Friday     3      NaN          DAY ST  42.325122 -71.107779   
4   Wednesday     0      NaN       GIBSON ST  42.297555 -71.059709   

                      Location  
0     (0.00000000, 0.00000000)  
1  (42.33081300, -71.05136800)  
2  (42.23949100, -71.13595400)  
3  (42.32512200, -71.10777900)  
4  (42.29755500, -71.05970900)

## DATA CLEANING PROCESS

In [4]:
df.shape

(529027, 17)

In [5]:
df.isnull().sum()

INCIDENT_NUMBER             0
OFFENSE_CODE                0
OFFENSE_CODE_GROUP     102188
OFFENSE_DESCRIPTION         0
DISTRICT                 2463
REPORTING_AREA              0
SHOOTING               425093
OCCURRED_ON_DATE            0
YEAR                        0
MONTH                       0
DAY_OF_WEEK                 0
HOUR                        0
UCR_PART               102298
STREET                  21487
Lat                     30305
Long                    30305
Location                    0
dtype: int64

In [6]:
df.drop(['OFFENSE_CODE_GROUP','SHOOTING','UCR_PART'], axis= 'columns', inplace=True)
df.head()

INCIDENT_NUMBER  OFFENSE_CODE        OFFENSE_DESCRIPTION  DISTRICT  \
0       TESTTEST2           423       ASSAULT - AGGRAVATED  External   
1       S97333701          3301             VERBAL DISPUTE        C6   
2       S47513131          2647  THREATS TO DO BODILY HARM       E18   
3       I92102201          3301             VERBAL DISPUTE       E13   
4       I92097173          3115         INVESTIGATE PERSON       C11   

  REPORTING_AREA     OCCURRED_ON_DATE  YEAR  MONTH DAY_OF_WEEK  HOUR  \
0                 2019-10-16 00:00:00  2019     10   Wednesday     0   
1            915  2020-07-18 14:34:00  2020      7    Saturday    14   
2            530  2020-06-24 10:15:00  2020      6   Wednesday    10   
3            583  2019-12-20 03:08:00  2019     12      Friday     3   
4            355  2019-10-23 00:00:00  2019     10   Wednesday     0   

           STREET        Lat       Long                     Location  
0    RIVERVIEW DR        NaN        NaN     (0.00000000, 0.00000000)  
1  MARY BOYLE WAY  42.330813 -71.051368  (42.33081300, -71.05136800)  
2    READVILLE ST  42.239491 -71.135954  (42.23949100, -71.13595400)  
3          DAY ST  42.325122 -71.107779  (42.32512200, -71.10777900)  
4       GIBSON ST  42.297555 -71.059709  (42.29755500, -71.05970900)

In [7]:
df.shape

(529027, 14)

In [8]:
df.isnull().sum()

INCIDENT_NUMBER            0
OFFENSE_CODE               0
OFFENSE_DESCRIPTION        0
DISTRICT                2463
REPORTING_AREA             0
OCCURRED_ON_DATE           0
YEAR                       0
MONTH                      0
DAY_OF_WEEK                0
HOUR                       0
STREET                 21487
Lat                    30305
Long                   30305
Location                   0
dtype: int64

In [9]:
df.dropna(inplace=True)

In [10]:
df.isnull().sum()

INCIDENT_NUMBER        0
OFFENSE_CODE           0
OFFENSE_DESCRIPTION    0
DISTRICT               0
REPORTING_AREA         0
OCCURRED_ON_DATE       0
YEAR                   0
MONTH                  0
DAY_OF_WEEK            0
HOUR                   0
STREET                 0
Lat                    0
Long                   0
Location               0
dtype: int64

In [11]:
df.shape

(486653, 14)

In [12]:
df.head()

INCIDENT_NUMBER  OFFENSE_CODE                         OFFENSE_DESCRIPTION  \
1       S97333701          3301                              VERBAL DISPUTE   
2       S47513131          2647                   THREATS TO DO BODILY HARM   
3       I92102201          3301                              VERBAL DISPUTE   
4       I92097173          3115                          INVESTIGATE PERSON   
5       I92094519          3126  WARRANT ARREST - OUTSIDE OF BOSTON WARRANT   

  DISTRICT REPORTING_AREA     OCCURRED_ON_DATE  YEAR  MONTH DAY_OF_WEEK  HOUR  \
1       C6            915  2020-07-18 14:34:00  2020      7    Saturday    14   
2      E18            530  2020-06-24 10:15:00  2020      6   Wednesday    10   
3      E13            583  2019-12-20 03:08:00  2019     12      Friday     3   
4      C11            355  2019-10-23 00:00:00  2019     10   Wednesday     0   
5      D14            765  2019-11-22 07:50:00  2019     11      Friday     7   

           STREET        Lat       Long                     Location  
1  MARY BOYLE WAY  42.330813 -71.051368  (42.33081300, -71.05136800)  
2    READVILLE ST  42.239491 -71.135954  (42.23949100, -71.13595400)  
3          DAY ST  42.325122 -71.107779  (42.32512200, -71.10777900)  
4       GIBSON ST  42.297555 -71.059709  (42.29755500, -71.05970900)  
5       BROOKS ST  42.355120 -71.162678  (42.35512000, -71.16267800)

This is a crime report in the city of bOston. The federal goverment are trying to figure out how to tackle the increasing crime rate in Boston. Therefore, answers to the following questions are needed
1. what is the most common crime noticed in the city?
2. what year has the highest amount of crime recorded?
3. prior to the above question, in what month did most of the crime take place and on what day?
4. around what hour are these crimes likely to be committed?

In [13]:
df.OFFENSE_DESCRIPTION.value_counts().head(10)

INVESTIGATE PERSON                       31440
SICK/INJURED/MEDICAL - PERSON            27820
VERBAL DISPUTE                           26721
M/V - LEAVING SCENE - PROPERTY DAMAGE    22767
VANDALISM                                22735
ASSAULT SIMPLE - BATTERY                 18625
INVESTIGATE PROPERTY                     18002
TOWED MOTOR VEHICLE                      16803
THREATS TO DO BODILY HARM                14435
LARCENY THEFT FROM BUILDING              13868
Name: OFFENSE_DESCRIPTION, dtype: int64

## What is the most common crime noticed in the city?

According to our analysis, the most common crime in Boston is the VERBAL ABUSE kind. But the most reason for 911 calls are to report a sick,injured or need medical attention immediately. The following are the five major crimes in the city of Boston:

 * VERBAL DISPTE
 * PROPERTY DAMAGE
 * VANDALISM
 * BATTERY
 * THREATS TO BODILY HARM

In [14]:
df.head()

INCIDENT_NUMBER  OFFENSE_CODE                         OFFENSE_DESCRIPTION  \
1       S97333701          3301                              VERBAL DISPUTE   
2       S47513131          2647                   THREATS TO DO BODILY HARM   
3       I92102201          3301                              VERBAL DISPUTE   
4       I92097173          3115                          INVESTIGATE PERSON   
5       I92094519          3126  WARRANT ARREST - OUTSIDE OF BOSTON WARRANT   

  DISTRICT REPORTING_AREA     OCCURRED_ON_DATE  YEAR  MONTH DAY_OF_WEEK  HOUR  \
1       C6            915  2020-07-18 14:34:00  2020      7    Saturday    14   
2      E18            530  2020-06-24 10:15:00  2020      6   Wednesday    10   
3      E13            583  2019-12-20 03:08:00  2019     12      Friday     3   
4      C11            355  2019-10-23 00:00:00  2019     10   Wednesday     0   
5      D14            765  2019-11-22 07:50:00  2019     11      Friday     7   

           STREET        Lat       Long                     Location  
1  MARY BOYLE WAY  42.330813 -71.051368  (42.33081300, -71.05136800)  
2    READVILLE ST  42.239491 -71.135954  (42.23949100, -71.13595400)  
3          DAY ST  42.325122 -71.107779  (42.32512200, -71.10777900)  
4       GIBSON ST  42.297555 -71.059709  (42.29755500, -71.05970900)  
5       BROOKS ST  42.355120 -71.162678  (42.35512000, -71.16267800)

In [15]:
df.YEAR.value_counts().plot(kind='bar')

<AxesSubplot:>

In [16]:
year17=df[df.YEAR.isin([2017])]
year17.OFFENSE_DESCRIPTION.value_counts()

INVESTIGATE PERSON                           6340
SICK/INJURED/MEDICAL - PERSON                5914
VANDALISM                                    4584
M/V - LEAVING SCENE - PROPERTY DAMAGE        4521
VERBAL DISPUTE                               4387
                                             ... 
PROSTITUTION - ASSISTING OR PROMOTING           1
PRISONER ATTEMPT TO RESCUE                      1
DRUGS - CLASS D TRAFFICKING OVER 50 GRAMS       1
HUMAN TRAFFICKING - INVOLUNTARY SERVITUDE       1
FIREARM/WEAPON - LOST                           1
Name: OFFENSE_DESCRIPTION, Length: 191, dtype: int64

In [17]:
year16=df[df.YEAR.isin([2016])]
year16.OFFENSE_DESCRIPTION.value_counts()

INVESTIGATE PERSON                              5514
SICK/INJURED/MEDICAL - PERSON                   5208
VANDALISM                                       4742
M/V - LEAVING SCENE - PROPERTY DAMAGE           4430
ASSAULT SIMPLE - BATTERY                        4162
                                                ... 
AUTO THEFT OTHER                                   1
DRUGS - CLASS D TRAFFICKING OVER 50 GRAMS          1
A&B HANDS, FEET, ETC.  - MED. ATTENTION REQ.       1
PRISONER ESCAPE / ESCAPE & RECAPTURE               1
AUTO THEFT - OUTSIDE - RECOVERED IN BOSTON         1
Name: OFFENSE_DESCRIPTION, Length: 208, dtype: int64

In [18]:
year15=df[df.YEAR.isin([2015])]
year15.OFFENSE_DESCRIPTION.value_counts()

VANDALISM                                2623
M/V - LEAVING SCENE - PROPERTY DAMAGE    2469
INVESTIGATE PERSON                       2458
SICK/INJURED/MEDICAL - PERSON            2323
ASSAULT SIMPLE - BATTERY                 2308
                                         ... 
FIREARM/WEAPON - CARRY - SELL - RENT        1
PROPERTY - CONCEALING LEASED                1
PROTECTIVE CUSTODY / SAFEKEEPING            1
ASSAULT D/W - KNIFE ON POLICE OFFICER       1
WEAPON - FIREARM - SALE / TRAFFICKING       1
Name: OFFENSE_DESCRIPTION, Length: 213, dtype: int64

In [19]:
year18=df[df.YEAR.isin([2018])]
year18.OFFENSE_DESCRIPTION.value_counts()

SICK/INJURED/MEDICAL - PERSON                 6445
INVESTIGATE PERSON                            5248
ASSAULT SIMPLE - BATTERY                      4568
VERBAL DISPUTE                                4362
M/V - LEAVING SCENE - PROPERTY DAMAGE         4347
                                              ... 
EXPLOSIVES - TURNED IN OR FOUND                  2
PRISONER ESCAPE / ESCAPE & RECAPTURE             2
FIREARM/WEAPON - ACCIDENTAL INJURY / DEATH       2
PROSTITUTION - ASSISTING OR PROMOTING            1
CONTRIBUTING TO DELINQUENCY OF MINOR             1
Name: OFFENSE_DESCRIPTION, Length: 184, dtype: int64

In [20]:
year19=df[df.YEAR.isin([2019])]
year19.OFFENSE_DESCRIPTION.value_counts()

SICK/INJURED/MEDICAL - PERSON                 5912
INVESTIGATE PERSON                            5798
VERBAL DISPUTE                                5278
M/V - LEAVING SCENE - PROPERTY DAMAGE         4332
VANDALISM                                     3865
                                              ... 
FIREARM/WEAPON - ACCIDENTAL INJURY / DEATH       1
BIOLOGICAL THREATS                               1
WEAPON - FIREARM - SALE / TRAFFICKING            1
MANSLAUGHTER - VEHICLE - NEGLIGENCE              1
PRISONER ESCAPE / ESCAPE & RECAPTURE             1
Name: OFFENSE_DESCRIPTION, Length: 220, dtype: int64

In [21]:
year20=df[df.YEAR.isin([2020])]
year20.OFFENSE_DESCRIPTION.value_counts()

VERBAL DISPUTE                                7150
INVESTIGATE PERSON                            6082
ASSAULT - SIMPLE                              4134
SICK ASSIST                                   3524
VANDALISM                                     2900
                                              ... 
OBSCENE PHONE CALLS                              2
FIREARM/WEAPON - ACCIDENTAL INJURY / DEATH       2
FIREARM/WEAPON - LOST                            2
Justifiable Homicide                             1
BIOLOGICAL THREATS                               1
Name: OFFENSE_DESCRIPTION, Length: 130, dtype: int64

In [22]:
yearcount=df['YEAR'].groupby(df['YEAR']).agg('count')

## What year has the highest amount of crime recorded?

The year in which the most crimes was recorded in Boston was in 2017 with a total of 93437 crimes reported. The following are the breakdowns  of the the years and amount of crimes recorded.

| YEARS       |      CRIMES RECORDED |
|----------   |---------------------|
|2017         |        93437         | 
|2016         |        91764         |
|2018         |         91540        |
|2019         |         89954        |
|2020         |         68508        |
|2015         |         51450        |


According to our research, the rate of these crimes do change with every year. See table below for more information.


| YEARS       |     TOP CRIME  |
|----------   |---------------------|
|2017         |       VANDALISM | 
|2016         |        VANDALISM          |
|2018         |         BATTERY        |
|2019         |         VERBAL DISPUTE        |
|2020         |         VERBAL DISPUTE        |
|2015         |         VANDALISM       |

In [23]:
year17.head()

INCIDENT_NUMBER  OFFENSE_CODE              OFFENSE_DESCRIPTION DISTRICT  \
3845      I192074488           619               LARCENY ALL OTHERS      C11   
4729      I192073511          1107            FRAUD - IMPERSONATION       B3   
5047      I192073187          2629                       HARASSMENT       C6   
5304      I192072907           802         ASSAULT SIMPLE - BATTERY       D4   
5311      I192072900          1102  FRAUD - FALSE PRETENSE / SCHEME       D4   

     REPORTING_AREA     OCCURRED_ON_DATE  YEAR  MONTH DAY_OF_WEEK  HOUR  \
3845            351  2017-08-23 00:00:00  2017      8   Wednesday     0   
4729            435  2017-02-21 00:01:00  2017      2     Tuesday     0   
5047            231  2017-07-13 00:00:00  2017      7    Thursday     0   
5304            171  2017-09-01 16:32:00  2017      9      Friday    16   
5311            151  2017-09-01 00:00:00  2017      9      Friday     0   

            STREET        Lat       Long                     Location  
3845      ADAMS ST  42.300605 -71.059230  (42.30060526, -71.05923027)  
4729  ARMANDINE ST  42.284315 -71.074108  (42.28431486, -71.07410838)  
5047    E FIFTH ST  42.333989 -71.032606  (42.33398889, -71.03260574)  
5304  HARRISON AVE  42.335119 -71.074917  (42.33511904, -71.07491710)  
5311    WARREN AVE  42.345163 -71.071291  (42.34516350, -71.07129114)

In [24]:
year17.MONTH.unique()

array([ 8,  2,  7,  9, 11, 12,  3,  5,  1,  6,  4, 10], dtype=int64)

In [25]:
year17['MONTH'].groupby(year17['MONTH']).agg('count').head()

MONTH
1    7457
2    6852
3    7531
4    7485
5    8081
Name: MONTH, dtype: int64

In [26]:
year20.MONTH.value_counts().head()

8     7400
1     7092
9     7058
10    6971
7     6832
Name: MONTH, dtype: int64

In [27]:
df.MONTH.value_counts().head()

8     48703
7     47519
9     46943
10    46140
6     43170
Name: MONTH, dtype: int64

In [28]:
df.DAY_OF_WEEK.value_counts(

Friday       74000
Wednesday    71250
Thursday     70696
Tuesday      70153
Monday       70110
Saturday     68412
Sunday       62032
Name: DAY_OF_WEEK, dtype: int64

## Prior to the above question, in what month did most of the crime take place and on what day?

 * Prior to the last question which says 2017 has the highest crime recorded. In 2017, the month with the highest crime recorded is the month of october with a total of 8449 crimes recorded.  
 * In the case of summing all the years together, the month of october still has the most crime recorded with a total of 48703 crimes recorded.
 * In the case of 2015, the month with the highest crime recorded was August with a total of 8085 crimes recorded.
 * In 2018, the month with the highest crime recorded is the month of May with a total of 8360 crimes recorded.
 * For 2016,2017,2019 and 2020, the month with the highest number of crime recorded is october.
 
According to our analysis, the days in which the most crimes were reported on is Fridays, from 2015 down to 2020. It has a total number of 74,000 crimes reported.

In [29]:
df.head()

INCIDENT_NUMBER  OFFENSE_CODE                         OFFENSE_DESCRIPTION  \
1       S97333701          3301                              VERBAL DISPUTE   
2       S47513131          2647                   THREATS TO DO BODILY HARM   
3       I92102201          3301                              VERBAL DISPUTE   
4       I92097173          3115                          INVESTIGATE PERSON   
5       I92094519          3126  WARRANT ARREST - OUTSIDE OF BOSTON WARRANT   

  DISTRICT REPORTING_AREA     OCCURRED_ON_DATE  YEAR  MONTH DAY_OF_WEEK  HOUR  \
1       C6            915  2020-07-18 14:34:00  2020      7    Saturday    14   
2      E18            530  2020-06-24 10:15:00  2020      6   Wednesday    10   
3      E13            583  2019-12-20 03:08:00  2019     12      Friday     3   
4      C11            355  2019-10-23 00:00:00  2019     10   Wednesday     0   
5      D14            765  2019-11-22 07:50:00  2019     11      Friday     7   

           STREET        Lat       Long                     Location  
1  MARY BOYLE WAY  42.330813 -71.051368  (42.33081300, -71.05136800)  
2    READVILLE ST  42.239491 -71.135954  (42.23949100, -71.13595400)  
3          DAY ST  42.325122 -71.107779  (42.32512200, -71.10777900)  
4       GIBSON ST  42.297555 -71.059709  (42.29755500, -71.05970900)  
5       BROOKS ST  42.355120 -71.162678  (42.35512000, -71.16267800)

In [30]:
df.HOUR.min()

0

In [31]:
df.HOUR.value_counts()

17    30785
16    30214
18    30072
12    28881
19    26554
14    26208
13    25766
0     25597
15    25275
11    25116
10    24740
20    24373
9     22509
21    21849
22    19889
8     19601
23    16225
1     13586
7     13404
2     11235
6      7502
3      6927
4      5222
5      5123
Name: HOUR, dtype: int64

In [32]:
hour=df[df.HOUR==17]
hour.head()

INCIDENT_NUMBER  OFFENSE_CODE                      OFFENSE_DESCRIPTION  \
12        I20207883          3115                       INVESTIGATE PERSON   
32        I20000994          3005                              SICK ASSIST   
154      I192078518          3503  MISSING PERSON - NOT REPORTED - LOCATED   
155      I192078517          3301                           VERBAL DISPUTE   
156      I192078516          3301                           VERBAL DISPUTE   

    DISTRICT REPORTING_AREA     OCCURRED_ON_DATE  YEAR  MONTH DAY_OF_WEEK  \
12        C6            914  2020-04-18 17:11:00  2020      4    Saturday   
32        A7             28  2020-01-04 17:50:00  2020      1    Saturday   
154       E5            672  2019-09-28 17:47:00  2019      9    Saturday   
155       B3            445  2019-09-28 17:33:00  2019      9    Saturday   
156       B2            330  2019-09-28 17:58:00  2019      9    Saturday   

     HOUR          STREET        Lat       Long                     Location  
12     17  OLD COLONY AVE  42.325573 -71.052481  (42.32557300, -71.05248100)  
32     17     MERIDIAN ST  42.371005 -71.038976  (42.37100500, -71.03897600)  
154    17      TYNDALE ST  42.287186 -71.136805  (42.28718557, -71.13680491)  
155    17    GREENWOOD ST  42.300077 -71.079902  (42.30007731, -71.07990164)  
156    17   BLUE HILL AVE  42.307036 -71.084102  (42.30703587, -71.08410227)

 * Based on our analysis, it been confirmed that most of these crimes usually occur around the hours of 4pm to 7pm with a total of 117625 crimes recorded within these hours. 
 * The hour with the most crime recorded is 5pm with a total number of 30785 crimes. 
 * The crime with the highest number of records around 5pm is Proprty Damage.